# nixpacks.toml
# This is the single, authoritative source of truth for building and starting.

# Explicitly declare the languages to use. This removes all auto-detection ambiguity.
providers = ["python", "node"]

[phases.setup]
# Define the exact language versions to use.
nixPkgs = ["pkgs.python311", "pkgs.nodejs-18_x"]

[phases.install]
# Specify the exact install commands in the correct order.
cmds = [
    "pip install -r backend/requirements.txt",
    "npm --prefix frontend install" # Use --prefix to be more explicit
]

[phases.build]
# Specify the frontend build command.
cmds = ["npm --prefix frontend run build"]

# Define the start command directly here, replacing the need for a Procfile.
[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
