# nixpacks.toml
# This is the single source of truth for building and starting the application.

[phases.setup]
# Define the exact language versions to use.
# This prevents auto-detection errors.
nixPkgs = ["pkgs.python311", "pkgs.nodejs-18_x"]

[phases.install]
# Specify the exact install commands in the correct order.
cmds = [
    "pip install -r backend/requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
# Specify the frontend build command.
cmds = ["cd frontend && npm run build"]

# Define the start command directly here.
# This replaces the Procfile.
[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
