services:
  - type: pserv
    name: sra-db
    dockerImage: postgres
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: sra_db
      - key: POSTGRES_USER
        value: user
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: PGDATA
        value: /var/lib/postgresql/data/pgdata

  - type: web
    name: sra-backend
    env: python
    plan: free
    repo: https://github.com/your-username/your-repo-name  # Replace with your actual repo URL
    branch: main
    healthCheckPath: /health
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: sra-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4

  - type: web
    name: sra-frontend
    env: node
    plan: free
    repo: https://github.com/your-username/your-repo-name  # Replace with your actual repo URL
    branch: main
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/build"
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: sra-backend
          property: url
    routes:
      - type: rewrite
        source: /ask/*
        destination: https://sra-backend.onrender.com/ask/
      - type: rewrite
        source: /upload_file/*
        destination: https://sra-backend.onrender.com/upload_file/
      - type: rewrite
        source: /*
        destination: /index.html
